apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'frontend'
spec:
  project: default
  source:
    repoURL: 'https://github.com/EchipaIDP/do-k8s-config.git'
    path: frontend
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: 860148e2737acaf88e19d6fc6786b43075c448cf
      values: |-
        image:
          tag: latest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: idp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
