apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-app
          image: {{ .Values.image.auth }}:{{ .Values.authImage.tag }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080