apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.service.authHost }}
      secretName: auth-tls
  rules:
    - host: {{ .Values.service.authHost }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: auth-service
                port:
                  number: 8080
