apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.service.bookHost }}
      secretName: book-tls
  rules:
    - host: {{ .Values.service.bookHost }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: book-service
                port:
                  number: 8080
